---
title: "Robust estimates of the infectiousness profile and serial interval distributions of SARS-CoV-2"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: simplex

---
<script>
$("body").on("shown.bs.tab", "a[data-toggle='tab']", function(e) {
   Shiny.setInputValue("active_tab", $(this).attr('id'));
})
</script>

```{r setup, echo= FALSE}
library(dplyr)
library(ggthemes)
library(plotly)
library(purrr)
library(shiny)
library(shinyWidgets)
source("R/utils.R")
cowling <- readRDS("data/cowling_data_cleaned.rds")
sn <- readRDS("processed_stanfits/skew_normal/release/best_si_skew_normal.rds")


```
Sidebar {.sidebar}
======================================================================

```{r}
selectInput(
  'TOST Distribution', label = 'Select a distribution',
  choices = c("NF", "skew normal", "gamma"),
  selected = "skew normal",
  multiple = FALSE
)

```

Compare models
======================================================================

Row 
-----------------------------------------------------------------------

### Baseline

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[8]], FALSE, FALSE, FALSE)
})
```


### Baseline + mixture

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[7]], TRUE, FALSE, FALSE)
})
```

Row 
-----------------------------------------------------------------------

### Baseline + recall

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[6]], FALSE, TRUE, FALSE)
})
```

### Baseline + mixture + recall

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[5]], TRUE, TRUE, FALSE)
})
```

Row 
-----------------------------------------------------------------------

### Baseline + isol

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[4]], FALSE, FALSE, TRUE)
})
```

### Baseline + isol + mixture

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[3]], TRUE, FALSE, TRUE)
})
```

Row 
-----------------------------------------------------------------------

### Baseline + isol + recall

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[2]], FALSE, TRUE, TRUE)
})
```

### Baseline + isol + mixture + recall

```{r}
renderPlot({
  plot_fitted_si(cowling, sn[[1]], TRUE, TRUE, TRUE)
})
```


Compare model fit across data-sets
======================================================================

Row 
-----------------------------------------------------------------------

### Full data-set

```{r}
```


### Discrete pairs

```{r}
```


Row 
-----------------------------------------------------------------------

### xxxx

```{r}
```


### yyyy

```{r}
```
